trigger:
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    publishExtension: ${{ parameters.publishExtension }}
    buildSteps:
      - script: npm i -g npm@8.15.1
        displayName: npm install npm@8.15.1

      - script: npm ci
        displayName: Install dependencies

      - script: npm run compile
        displayName: Compile
